export const HTTP_RESPONSE_CODE = {
    NOT_FOUND: 404,
    CREATED: 201,
    CONFLICT: 409,
    BAD_REQUEST: 400,
    SUCCESS: 200,
    UNAUTHORIZED: 401,
    SERVER_ERROR: 500,
}

export const APP_ERROR_MESSAGE = {
    serverError: 'Something went wrong, try again later',
    userAlreadyExist: 'The email is already registered',
    createdUser: 'User created successfully',
    updatedUser: 'User details updated successfully',
    eventCreated: 'Event created successfully',
    reviewCreated: 'Review created successfully',
    userAuthenticated: 'User Authenticated successfully',
    userReturned: 'User Returned successfully',
    usersReturned: 'Users Returned successfully',
    logOutSucces: 'User logged out successfully',
    userNotFound: 'User is not found',
    categoryExists: 'The category has been already added',
    categoryCreated: 'Category created successfully',
    categoryFound: 'Category found successfully',
    categoryDeleted: 'Category deleted successfully',
    categoryUpdated: 'Category updated successfully',
    transactionsFetched: 'Transactions fetched successfully',
    transactionCreated: 'Transaction created successfully',
    transactionUpdated: 'Transaction updated successfully',
    transactionDeleted: 'Transaction deleted successfully',
    goalCreated: 'Goal created successfully',
    goalUpdated: 'Goal updated successfully',
    goalDeleted: 'Goal deleted successfully',
    goalFound: 'Goal found successfully',
    goalNotFound: 'Goal not found',
    budgetCreated: 'Budget created successfully',
    budgetUpdated: 'Budget updated successfully',
    budgetDeleted: 'Budget deleted successfully',
    budgetFound: 'Budget found successfully',
    eventsReturned: 'Events Returned successfully',
    reviewsReturned: 'Reviews Returned successfully',
    userDoesntExist: 'User does not exist',
    eventDoesntExist: 'Event does not exist',
    invalidCredentials: 'Invalid user email or password',
    invalidEmail: 'Enter a valid email address',
    authheadermissing: 'No Authentication Header found in the request',
    tokenExpired: 'Authentication token is expired',
    actionNotAllowed: "You're not authroized to perform this action",
}
